### ISSUE TITLE
Deprecated syntax in gifti/subsref.m?

### ISSUE THREAD

**Issue by ftadel** [gllmflndn/gifti#1]
This line creates warnings in newer Matlab versions:
https://github.com/gllmflndn/gifti/blob/master/%40gifti/subsref.m#L45

Warning example, form the Brainstorm user forum: 
![image](https://user-images.githubusercontent.com/6920058/63703225-d2a84180-c828-11e9-88d9-8d8f4260bd77.png)

Do you need these () for anything here?

**Comment by gllmflndn** [comment]
Hello @ftadel,

Thanks for reaching out. Yes, the `()` are there for a reason: when `cdata` contains a memory-mapped object (`@file_array`). I'm already aware of this compatibility issue and the code has been fixed upstream in SPM where `@gifti` is taken from. I'll try to make a new release of this class soon. The change is:
```
-            varargout{1} = varargout{1}() + 1; % indices start at 1
+            varargout{1} = full(varargout{1}) + 1; % indices start at 1
```

**Comment by gllmflndn** [comment]
I pushed a number of of rather substantial changes that should fix your issue among other things. It would be great if you could test this new version and let me know if you observe any bug or unexpected side effect.
