### ISSUE TITLE
Error on Matlab 2023b

### ISSUE THREAD

**Issue by xmival00** [gllmflndn/gifti#14]
Matlab 2023b; Ubuntu 22.04 (64)

Running the first README example and fails on loading data using gifti function. 

Error - too many input arguments for a struct. 

Replicated also using any other nifti file.

Any suggestions on which Matlab versions might work?

Error using struct
Too many input arguments.

Error in gifti>giftistruct (line 132)
        struct(...

Error in gifti (line 108)
                this = gifti_read(varargin{1},giftistruct);
 
Error using struct
Invalid default value for property 'N' in class 'mtree':
Too many input arguments.

Error in nodeinfo (line 40)
    L = struct( lnk{:} );

Error in mtree_info (line 18)
        [LNK,LMAP,LOK] = nodeinfo();

Error in matlab.internal.editor.evaluateCode
 
Error using struct
Invalid default value for property 'N' in class 'mtree':
Too many input arguments.

Error in nodeinfo (line 40)
    L = struct( lnk{:} );

Error in mtree_info (line 18)
        [LNK,LMAP,LOK] = nodeinfo();

Error in matlab.internal.editor.evaluateCode
 
Error using struct
Invalid default value for property 'N' in class 'mtree':
Too many input arguments.

Error in nodeinfo (line 40)
    L = struct( lnk{:} );

Error in mtree_info (line 18)
        [LNK,LMAP,LOK] = nodeinfo();

Error in matlab.internal.editor.evaluateCode

**Comment by neurolabusc** [comment]
I just downloaded this repository, removed SPM from my path (as it also includes this GIfTI reader), added the github repository to my path, and everything works fine for me with a MacOS M2:

```
>> g = gifti('sujet01_Lwhite.surf.gii');
>> c = gifti('sujet01_Lwhite.shape.gii');
>> figure; plot(g,c);
>> ver
-----------------------------------------------------------------------------------------
MATLAB Version: 23.2.0.2365128 (R2023b)
MATLAB License Number: 40602193
Operating System: macOS  Version: 13.6 Build: 22G120 
Java Version: Java 1.8.0_382-b05 with Amazon.com Inc. OpenJDK 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------
MATLAB                                                Version 23.2        (R2023b)
Deep Learning Toolbox                                 Version 23.2        (R2023b)
Image Processing Toolbox                              Version 23.2        (R2023b)
Parallel Computing Toolbox                            Version 23.2        (R2023b)
Statistics and Machine Learning Toolbox               Version 23.2        (R2023b)
```

**Comment by gllmflndn** [comment]
It also works for me with MATLAB R2023b on Ubuntu 22.04. The error message is slightly odd: could it be that you have a function called `struct` in your MATLAB path that overshadows the builtin `struct`? You can check this with `which struct -all`. The `gifti` class comes with a `struct` method but it should not get on the way here.
